# Title of your blog; shows in the header
name: "Tyler Yasaka"

# Description of your content (will only be used on Google Search)
description: "Tyler's personal blog"

# Your name. Will show in your footer + sidebar
author: "Tyler Yasaka"

url: "https://tyleryasaka.me"
baseurl: ""

# A short presentation of yourself. Will show in the sidebar, under your name. Best usage would be between 30 to 50 words.
author-bio: "I'm a former software engineer transitioning to a career in medicine. During my free time, I pursue a lot of random interests that are changing pretty much all the time."

# Social Accounts (mine, as placeholders)

# twitter: YasakaTyler
github: tyleryasaka
linkedin: tyler-yasaka-79424070
soundcloud: incline-eight
keybase: tyleryasaka
email: contact@tyleryasaka.me

# Google Analytics (you may want to changes these with yours or even delete :)

# ga_domain: m3xm.github.io
# ga_tracking_id: UA-47727049-1

# Other (refer to http://jekyllrb.com/docs/home/ for further details on the below)

markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate

paginate: 10
paginate_path: "/page/:num"

# SCSS

sass:
  sass_dir: _scss
  style: :compressed
